apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kube-backup-s3
  namespace: kube-system
data:
  S3_ACCESS_KEY: <base64 s3 access key>
  S3_SECRET_KEY: <base64 s3 secret key>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-backup
  namespace: kube-system
data:
  S3_ALIAS: backup-minio
  S3_BUCKET: backup
  S3_ENDPOINT: http://backup.s3.tld:9001/

---